kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-django-service
spec:
  selector:
    app: {{ .Release.Name }}-django
  ports:
  - protocol: TCP
    port: {{ .Values.django.port }}
    targetPort: {{ .Values.django.port }}