apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django-np
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - nodePort: {{ .Values.django.nodePort }}
    port: {{ .Values.django.port }}
    protocol: TCP
    targetPort: {{ .Values.django.port }}
  selector:
    app: {{ .Release.Name }}-django
  sessionAffinity: None
  type: NodePort
