apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-mysql-service
  namespace:  {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-mysql
    version: {{ quote .Values.mysql.image.version  }}
  ports:
  - protocol: TCP
    port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}