apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-np
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - nodePort: {{ .Values.mysql.nodePort }}
      port: {{ .Values.mysql.port }}
      protocol: TCP
      targetPort: {{ .Values.mysql.port }}
  selector:
    app: {{ .Release.Name }}-mysql
    version: {{ quote .Values.mysql.image.version }}
  sessionAffinity: None
  type: NodePort
