apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-mysql
    version: {{ quote .Values.mysql.image.version  }}
data:
  my.cnf: |
    [mysqld]
    max_connections = 600
    read_buffer_size = 1048576
    net_read_timeout = 360
    net_write_timeout = 360
    max_connect_errors = 10000
    port = 3306