apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-initdb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-mysql
    version: {{ quote .Values.mysql.image.version  }}
data:
  initdb.sql: |-
    CREATE DATABASE IF NOT EXISTS {{ .Values.mysql.database }} ;