# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


imagePullSecrets: []
nameOverride: "crud"
fullnameOverride: ""

mysql:
  password: changeme
  database: djangodb
  nodePort: 30306
  port: 3306
  persistentVolumes:
    dbSize: 1Gi
  image:
    name: "mysql"
    imagePullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    version: "5.7"
  livenessProbe:
    tcpSocket:
      port: 3306
    initialDelaySeconds: 120
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 2
    timeoutSeconds: 3

django:
  nodePort: 30800
  port: 8000
  image:
    name: "achirita/crud"
    imagePullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    version: "alpine"
  livenessProbe:
    tcpSocket:
      port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 2
    timeoutSeconds: 3

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 100m
     memory: 400Mi
   requests:
     cpu: 100m
     memory: 400Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
